In [1]:
import torch
import torch.nn.functional as F

In [2]:
A_tilde = torch.tensor([
    [1, 1, 1, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 0, 0],
    [0, 1, 0, 1, 1],
    [0, 1, 0, 1, 1]
], dtype=torch.float32)

D_tilde = torch.tensor([
    [3, 0, 0, 0, 0],
    [0, 5, 0, 0, 0],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 3, 0],
    [0, 0, 0, 0, 3]
], dtype=torch.float32)

X = torch.tensor([
    [1, 2, 1, 2],
    [2, 1, 2, 1],
    [2, 2, 1, 1],
    [1, 1, 2, 2],
    [2, 1, 1, 1]
], dtype=torch.float32)

W = torch.tensor([
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1]
], dtype=torch.float32)

In [4]:
# Calculate D^(-1/2)
D_inv_sqrt = torch.diag(1.0 / torch.sqrt(torch.diag(D_tilde)))

# Calculate A_norm = D^(-1/2) * A * D^(-1/2)
A_norm = torch.mm(torch.mm(D_inv_sqrt, A_tilde), D_inv_sqrt)

# Perform GCN operation: X_new = A_norm * X * W
X_new = torch.mm(torch.mm(A_norm, X), W)

print("D^(-1/2):")
print(D_inv_sqrt)

print("\nA_norm = D^(-1/2) * A * D^(-1/2):")
print(A_norm)

print("\nGCN output X_new:")
print(X_new)

D^(-1/2):
tensor([[0.5774, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.4472, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5774, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5774, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.5774]])

A_norm = D^(-1/2) * A * D^(-1/2):
tensor([[0.3333, 0.2582, 0.3333, 0.0000, 0.0000],
        [0.2582, 0.2000, 0.2582, 0.2582, 0.2582],
        [0.3333, 0.2582, 0.3333, 0.0000, 0.0000],
        [0.0000, 0.2582, 0.0000, 0.3333, 0.3333],
        [0.0000, 0.2582, 0.0000, 0.3333, 0.3333]])

GCN output X_new:
tensor([[5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492],
        [7.1386, 7.1386, 7.1386, 7.1386, 7.1386, 7.1386, 7.1386, 7.1386],
        [5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492, 5.5492],
        [5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159],
        [5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159, 5.2159]])
